services:
  - type: web
    name: yt-summarizer
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python backend/app.py"
    envVars:
      - key: HF_TOKEN
        sync: false
